CREATE TABLE EMPLOYEE(
    EMPID INT PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(50),
    GENDER VARCHAR(6) CHECK CONSTRAINT(GENDER IN ('MALE','FEMALE','OTHER')),
    GL CHAR(2),
    DOJ DATE,
    DESIGNATION VARCHAR(50),
    EMPTYPE VARCHAR(30),
    EMPSTATUS VARCHAR(8) CHECK CONSTRAINT(EMPSTATUS IN ('ACTIVE','INACTIVE')),
    PROBPERIOD INT,
    PROBCOMPDATE DATE,
    TRAINPERIOD INT,
    CONTRACTEND DATE,
    SERVPERIOD INT,
    ISGM TINYINT(1),
    ISEXPAT TINYINT(1),
    RELEASEDATE DATE,
    LOCID REFERENCES LOCATION(LOCID),
    DOMID REFERENCES DOMAIN(DOMID),
    WORKSTATIONID VARCHAR(4),
    COMPID REFERENCES COMPENSATION(COMPID),
    PROJID REFERENCES PROJECT(PROJID),
    GRPID REFERENCES GROUP(GRPID)
);

CREATE TABLE GROUP(
    GRPID INT PRIMARY KEY AUTOINCREMENT,
    GM VARCHAR(50)
    DEPTID REFERENCES DEPARTMENT(DEPTID)
)

CREATE TABLE DEPARTMENT(
    DEPTID INT PRIMARY KEY AUTOINCREMENT,
    DEPARTMENT_NAME VARCHAR(30),
    HOD VARCHAR(50)
)


CREATE TABLE DOMAIN(
    DOMID INT PRIMARY KEY AUTOINCREMENT,
    USERID VARCHAR(10),
    EMAIL VARCHAR(50)
)

CREATE TABLE LOCATION(
    LOCID INT PRIMARY KEY AUTOINCREMENT,
    BRANCH VARCHAR(50),
    OFFICE VARCHAR(50)
);

CREATE TABLE COMPENSATION(
    COMPID INT PRIMARY KEY AUTOINCREMENT,
    CTC DECIMAL
);

CREATE TABLE PROJECT(
    PROJID INT PRIMARY KEY AUTOINCREMENT,
    PM VARCHAR(50)
);

CREATE TABLE FAMILYDETAILS(
    FAMILY_ID INT PRIMARY KEY AUTOINCREMENT,
    PROFILE_PIC VARCHAR(50),
    PANCARD_FILE VARCHAR(50),
    PANCARDNO VARCHAR(10),
    UAN_FILE VARCHAR(50),
    PRAN_FILE VARCHAR(50),
    ADHAAR_FILE VARCHAR(50),
    ADHAARNO VARCHAR(12),
    PASSPORT_FILE VARCHAR(50),
    PASSPORTNO VARACHAR(10),
    PLACE_OF_ISSUE VARCHAR(20),
    DATE_OF_ISSUE DATE,
    DATE_OF_EXPIRY DATE,

);

