CREATE TABLE EMPLOYEE(
    EMPID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPNAME VARCHAR(50) NOT NULL,
    GENDER ENUM ('M','F','O') NOT NULL,
    GRADE_LEVEL VARCHAR(2) NOT NULL,
    DOJ DATE NOT NULL,
    DESIGNATION VARCHAR(50),
    EMPTYPE ENUM('FULL-TIME','PART-TIME','CONTRACT') NOT NULL,
    EMPSTATUS ENUM('ACIVE','INACTIVE') NOT NULL,
    PROB_PERIOD INT,
    PROB_COMP_DATE DATE,
    TRAIN_PERIOD INT,
    CONTRACT_END DATE,
    SERV_PERIOD INT,
    ISGM TINYINT(1),
    ISEXPAT TINYINT(1),
    RELEASE_DATE DATE,
    FOREIGN KEY LOC_ID REFERENCES LOCATION(LOCID) ON DELETE CASCADE ON UPDATE CASCADE,
    DOMID REFERENCES DOMAIN(DOMID),
    WORKSTATIONID VARCHAR(4),
    COMPID REFERENCES COMPENSATION(COMPID),
    PROJID REFERENCES PROJECT(PROJID),
    GRPID REFERENCES GROUP(GRPID)
);

CREATE TABLE GROUP(
    GRPID INT PRIMARY KEY AUTO_INCREMENT,
    GM VARCHAR(50)
    DEPTID REFERENCES DEPARTMENT(DEPTID)
)

CREATE TABLE DEPARTMENT(
    DEPTID INT PRIMARY KEY AUTOINCREMENT,
    DEPARTMENT_NAME VARCHAR(30),
    HOD VARCHAR(50)
)


CREATE TABLE DOMAIN(
    DOMID INT PRIMARY KEY AUTOINCREMENT,
    USERID VARCHAR(10),
    EMAIL VARCHAR(50)
)

CREATE TABLE LOCATION(
    LOCID INT PRIMARY KEY AUTOINCREMENT,
    BRANCH VARCHAR(50),
    OFFICE VARCHAR(50)
);

CREATE TABLE COMPENSATION(
    COMPID INT PRIMARY KEY AUTOINCREMENT,
    CTC DECIMAL
);

CREATE TABLE PROJECT(
    PROJID INT PRIMARY KEY AUTOINCREMENT,
    PM VARCHAR(50)
);

CREATE TABLE EMPLOYEEDETAILS(
    PROFILE_PIC VARCHAR(50),
    PERMA_ADDR VARCHAR(100),
    PRIMARY_CONTACTNO VARCHAR(10),
    EMERGENCY_CONTACTNO VARCHAR(10),
    ADDR_PROOF VARCHAR(50),
    EMAIL_ID VARCHAR(30),
    DOB DATE,
    PRESENT_ADDR VARCHAR(100),
    NATIONALITY VARCHAR(20),
    BLOODGRP VARCHAR(3),
    DIFF_ABLED VARCHAR(3) CHECK CONSTRAINT (DIFF_ABLED IN ('YES','NO')),
    DIFF_ABLED_DOC VARCHAR(50),
    EMPID INT REFERENCES EMPDETAILS(EMPID)
);

CREATE TABLE FAMILYDETAILS(
    FAMILY_ID INT PRIMARY KEY AUTOINCREMENT,
    MARITAL_STAT ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED'),
    RELATION ENUM('SPOUSE', 'FATHER','MOTHER','BROTHER','SISTER','CHILD'),
    FAM_NAME VARCHAR(30),
    DOB DATE,
    OCCUPATION VARCHAR(30),
    CONTACTNO VARCHAR(10),
    MED_INSC ENUM('Y','N'),
    EMPID INT REFERENCES EMPDETAILS(EMPID)
);

CREATE TABLE EMPLOYEEDOCUMENTS(
    
    PANCARD_FILE VARCHAR(50),
    PANCARDNO VARCHAR(10),
    UAN_FILE VARCHAR(50),
    PRAN_FILE VARCHAR(50),
    ADHAAR_FILE VARCHAR(50),
    ADHAARNO VARCHAR(12),
    PASSPORT_FILE VARCHAR(50),
    PASSPORTNO VARACHAR(10),
    PLACE_OF_ISSUE VARCHAR(20),
    DATE_OF_ISSUE DATE,
    DATE_OF_EXPIRY DATE,
    BANK_NAME VARCHAR(30),
    ACC_NO DOUBLE,
    IFSC VARCHAR(12),
    PRIMARY_ACC ENUM('Y','N'),
    IS_ACTIVE ENUM('Y','N'),
    EMPID INT REFERENCES EMPDETAILS(EMPID)

);

CREATE TABLE QUALIFICATION_DETAILS(
    HIGHEST_QUAL VARCHAR(50),
    HIGHEST_QUAL_DOC VARCHAR(50),
    EMPID INT REFERENCES EMPDETAILS(EMPID)

);

CREATE TABLE PROF_DETAILS(
    PROF_DEL_ID INT AUTO_INCREMENT,
    NAME_OF_PREV_ORG VARCHAR(50),
    DESIGNATION VARCHAR(30),
    FROM_DATE DATE,
    TO_DATE DATE,
    RELEASE_LETTER_DOC VARCHAR(50),
    EXPERIENCE_CERT VARCHAR(50),
    REPORTING_STRUC VARCHAR(20),
    PROF_BODIES_MEMBER VARCHAR(50),
    SOCIAL_BODIES_MEMBER VARCHAR(50),
    EMPID INT REFERENCES EMPDETAILS(EMPID)
)